### ISSUE TITLE
Workloads dont match what's being shown in vscode

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#90]
follows up on #35 

intellij-kubernetes doesn't match what's being displayed in vscode.

For an OpenShift cluster: 

* ImageStreams should be shown after Pods
* DeploymentConfigs should be shown after ImageStreams
* BuildConfigs are missing

intellij-kubernetes:
![image](https://user-images.githubusercontent.com/25126/92121934-26b21280-edfb-11ea-8051-bd98629b9bef.png)

vscode:
![image](https://user-images.githubusercontent.com/25126/92122033-42b5b400-edfb-11ea-8b47-a1aa3d54a893.png)

**Comment by lstocchi** [comment]
I just want to mention that the vscode kubernetes extension doesn't provide those resources. They are added by the openshift tools extension.

**Comment by adietish** [comment]
@lstocchi I'd agree on this being minor. But shouldn't we match vscode as closely as possible?

**Comment by lstocchi** [comment]
As a personal opinion, the order is not that important for me and I wouldn't care much on it.

The important thing is to keep the same grouping (e.g having pods, deployment ... under workloads) and that's already done.

Even if you switch from Code to IJ and you need a specific resource, if the grouping is the same you don't feel lost, because when you open the workloads (or whatever) node it will be easy to find the resource you need even if they are in a different position (i mean we are talking about lists of 8-9 nodes, you see everything with a glance). 

Another thing i never understood is the ordering used in Code. They are not in alphabetical order, they are not in order of importance (otherwise i would not have put pods in almost last position), but they look like in random order. So maybe we can think of something different here.

Another point is the way the kubernetes extension in Code works. As a said previously it doesn't contain OpenShift resources by default, but they are added by the OpenShift extension. Now you have this extension installed and you see `ImageStream`, `DeploymentConfig` and `BuildConfigs` under `Pods`. But what if another user have another extension AB (in addition to the OpenShift ext) that add new nodes to workloads? The order may be different. 

Let's suppose that one day that extension AB will also be available in IJ and it will extend this one. 
You could end up with two trees in different node order because, in IJ, it will result in `(all k8s nodes) + (all OpenShift nodes) + (all AB nodes)`, and in Code (based on the installation order) you could have `(all k8s node) + (all AB nodes) + (all OpenShift nodes)`. 
So you could have solved nothing even by matching Code tree status right now.

BTW just my .2 cent, it can also match Code tree. i just commented because i saw you marked this as bug and I really don't see it as a bug. :)

**Comment by adietish** [comment]
Agreeing with @lstocchi I'll just add missing BuildConfigs in this issue.

**Comment by adietish** [comment]
closing as WONT_DO
